name: schedule
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # DateFormat
  intl: ">=0.15.0 <0.18.0"
  # Table Calendar
  #table_calendar: ^2.3.3
  # shared_preferences
  shared_preferences: ^0.5.6
  # Date Format
  date_format: ^1.0.6
  toast: ^0.1.5
  # sqlite
  #sqflite: ^1.2.0
  sqflite: ^1.3.0
  # Simple Animation
  simple_animations: ^1.3.8
  # Bloc
  flutter_bloc: ^3.2.0
  # Equatable
  equatable: ^1.1.1
  # Dio
  dio: ^3.0.9
  # Svg image
  #flutter_svg: ^0.17.4
  flutter_svg: ^0.19.0
  # Worm indicator
  worm_indicator: 0.2.1
  # Bottom Navigator
  google_nav_bar: ^2.1.0
  # DatePicker
  flutter_rounded_date_picker: ^1.0.4
  # Dialog
  awesome_dialog: ^0.1.3
  get_it: ^5.0.4

  crypto: ^2.1.5
  flutter_screenutil: ^4.0.2+5
  simple_gesture_detector: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MR
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
